/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IERC20MetadataInterface extends Interface {
  functions: {
    decimals: TypedFunctionDescription<{ encode([]: []): string }>;

    name: TypedFunctionDescription<{ encode([]: []): string }>;

    symbol: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class IERC20Metadata extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IERC20Metadata;
  attach(addressOrName: string): IERC20Metadata;
  deployed(): Promise<IERC20Metadata>;

  on(event: EventFilter | string, listener: Listener): IERC20Metadata;
  once(event: EventFilter | string, listener: Listener): IERC20Metadata;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IERC20Metadata;
  removeAllListeners(eventName: EventFilter | string): IERC20Metadata;
  removeListener(eventName: any, listener: Listener): IERC20Metadata;

  interface: IERC20MetadataInterface;

  functions: {
    decimals(): Promise<number>;

    name(): Promise<string>;

    symbol(): Promise<string>;
  };

  decimals(): Promise<number>;

  name(): Promise<string>;

  symbol(): Promise<string>;

  filters: {};

  estimate: {
    decimals(): Promise<BigNumber>;

    name(): Promise<BigNumber>;

    symbol(): Promise<BigNumber>;
  };
}
