/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ILatestAnswerGetter } from "./ILatestAnswerGetter";

export class ILatestAnswerGetterFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILatestAnswerGetter {
    return new Contract(address, _abi, signerOrProvider) as ILatestAnswerGetter;
  }
}

const _abi = [
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
