/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ILatestAnswerGetterInterface extends Interface {
  functions: {
    latestAnswer: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class ILatestAnswerGetter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ILatestAnswerGetter;
  attach(addressOrName: string): ILatestAnswerGetter;
  deployed(): Promise<ILatestAnswerGetter>;

  on(event: EventFilter | string, listener: Listener): ILatestAnswerGetter;
  once(event: EventFilter | string, listener: Listener): ILatestAnswerGetter;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ILatestAnswerGetter;
  removeAllListeners(eventName: EventFilter | string): ILatestAnswerGetter;
  removeListener(eventName: any, listener: Listener): ILatestAnswerGetter;

  interface: ILatestAnswerGetterInterface;

  functions: {
    latestAnswer(): Promise<BigNumber>;
  };

  latestAnswer(): Promise<BigNumber>;

  filters: {};

  estimate: {
    latestAnswer(): Promise<BigNumber>;
  };
}
