/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IPriceGetterCpmInterface extends Interface {
  functions: {
    getTokenToEthInputPrice: TypedFunctionDescription<{
      encode([tokens_sold]: [BigNumberish]): string;
    }>;
  };

  events: {};
}

export class IPriceGetterCpm extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IPriceGetterCpm;
  attach(addressOrName: string): IPriceGetterCpm;
  deployed(): Promise<IPriceGetterCpm>;

  on(event: EventFilter | string, listener: Listener): IPriceGetterCpm;
  once(event: EventFilter | string, listener: Listener): IPriceGetterCpm;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IPriceGetterCpm;
  removeAllListeners(eventName: EventFilter | string): IPriceGetterCpm;
  removeListener(eventName: any, listener: Listener): IPriceGetterCpm;

  interface: IPriceGetterCpmInterface;

  functions: {
    getTokenToEthInputPrice(tokens_sold: BigNumberish): Promise<BigNumber>;
  };

  getTokenToEthInputPrice(tokens_sold: BigNumberish): Promise<BigNumber>;

  filters: {};

  estimate: {
    getTokenToEthInputPrice(tokens_sold: BigNumberish): Promise<BigNumber>;
  };
}
