/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IPriceGetterCpm } from "./IPriceGetterCpm";

export class IPriceGetterCpmFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPriceGetterCpm {
    return new Contract(address, _abi, signerOrProvider) as IPriceGetterCpm;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokens_sold",
        type: "uint256"
      }
    ],
    name: "getTokenToEthInputPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
