/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ISynthetixExchangeRates } from "./ISynthetixExchangeRates";

export class ISynthetixExchangeRatesFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISynthetixExchangeRates {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISynthetixExchangeRates;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "sourceCurrencyKey",
        type: "bytes32"
      },
      {
        internalType: "uint256",
        name: "sourceAmount",
        type: "uint256"
      },
      {
        internalType: "bytes32",
        name: "destinationCurrencyKey",
        type: "bytes32"
      }
    ],
    name: "effectiveValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "currencyKey",
        type: "bytes32"
      }
    ],
    name: "rateForCurrency",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
