/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface MockFallbackOracleInterface extends Interface {
  functions: {
    getAssetPrice: TypedFunctionDescription<{
      encode([_asset]: [string]): string;
    }>;
  };

  events: {};
}

export class MockFallbackOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): MockFallbackOracle;
  attach(addressOrName: string): MockFallbackOracle;
  deployed(): Promise<MockFallbackOracle>;

  on(event: EventFilter | string, listener: Listener): MockFallbackOracle;
  once(event: EventFilter | string, listener: Listener): MockFallbackOracle;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): MockFallbackOracle;
  removeAllListeners(eventName: EventFilter | string): MockFallbackOracle;
  removeListener(eventName: any, listener: Listener): MockFallbackOracle;

  interface: MockFallbackOracleInterface;

  functions: {
    getAssetPrice(_asset: string): Promise<BigNumber>;
  };

  getAssetPrice(_asset: string): Promise<BigNumber>;

  filters: {};

  estimate: {
    getAssetPrice(_asset: string): Promise<BigNumber>;
  };
}
