/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";
import { BigNumberish } from "ethers/utils";

import { TransactionOverrides } from ".";
import { MockFallbackOracle } from "./MockFallbackOracle";

export class MockFallbackOracleFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _price: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<MockFallbackOracle> {
    return super.deploy(_price, overrides) as Promise<MockFallbackOracle>;
  }
  getDeployTransaction(
    _price: BigNumberish,
    overrides?: TransactionOverrides
  ): UnsignedTransaction {
    return super.getDeployTransaction(_price, overrides);
  }
  attach(address: string): MockFallbackOracle {
    return super.attach(address) as MockFallbackOracle;
  }
  connect(signer: Signer): MockFallbackOracleFactory {
    return super.connect(signer) as MockFallbackOracleFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockFallbackOracle {
    return new Contract(address, _abi, signerOrProvider) as MockFallbackOracle;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "constructor"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_asset",
        type: "address"
      }
    ],
    name: "getAssetPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161010c38038061010c8339818101604052602081101561003357600080fd5b505160805260805160bd61004f600039806065525060bd6000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063b3596f0714602d575b600080fd5b605060048036036020811015604157600080fd5b50356001600160a01b03166062565b60408051918252519081900360200190f35b507f00000000000000000000000000000000000000000000000000000000000000009056fea26469706673582212203456bd60798a9596758ce8ee404f9076ed6e588ec4734e6ab8c1b1796a67884264736f6c63430006060033";
