/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface TokenEthCPMPriceProviderInterface extends Interface {
  functions: {
    latestAnswer: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class TokenEthCPMPriceProvider extends Contract {
  connect(
    signerOrProvider: Signer | Provider | string
  ): TokenEthCPMPriceProvider;
  attach(addressOrName: string): TokenEthCPMPriceProvider;
  deployed(): Promise<TokenEthCPMPriceProvider>;

  on(event: EventFilter | string, listener: Listener): TokenEthCPMPriceProvider;
  once(
    event: EventFilter | string,
    listener: Listener
  ): TokenEthCPMPriceProvider;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): TokenEthCPMPriceProvider;
  removeAllListeners(eventName: EventFilter | string): TokenEthCPMPriceProvider;
  removeListener(eventName: any, listener: Listener): TokenEthCPMPriceProvider;

  interface: TokenEthCPMPriceProviderInterface;

  functions: {
    latestAnswer(): Promise<BigNumber>;
  };

  latestAnswer(): Promise<BigNumber>;

  filters: {};

  estimate: {
    latestAnswer(): Promise<BigNumber>;
  };
}
